In [3]:
pip install --upgrade category_encoders

Collecting category_encoders
  Downloading category_encoders-2.3.0-py2.py3-none-any.whl (82 kB)
Requirement already satisfied: patsy>=0.5.1 in c:\users\stefa\anaconda3\lib\site-packages (from category_encoders) (0.5.1)
Requirement already satisfied: pandas>=0.21.1 in c:\users\stefa\anaconda3\lib\site-packages (from category_encoders) (1.2.4)
Requirement already satisfied: scikit-learn>=0.20.0 in c:\users\stefa\anaconda3\lib\site-packages (from category_encoders) (0.24.1)
Requirement already satisfied: numpy>=1.14.0 in c:\users\stefa\anaconda3\lib\site-packages (from category_encoders) (1.20.1)
Requirement already satisfied: scipy>=1.0.0 in c:\users\stefa\anaconda3\lib\site-packages (from category_encoders) (1.6.2)
Requirement already satisfied: statsmodels>=0.9.0 in c:\users\stefa\anaconda3\lib\site-packages (from category_encoders) (0.12.2)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\users\stefa\anaconda3\lib\site-packages (from pandas>=0.21.1->category_encoders) (2.8.1)
Requirement already satisfied: pytz>=2017.3 in c:\users\stefa\anaconda3\lib\site-packages (from pandas>=0.21.1->category_encoders) (2021.1)
Requirement already satisfied: six in c:\users\stefa\anaconda3\lib\site-packages (from patsy>=0.5.1->category_encoders) (1.15.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\stefa\anaconda3\lib\site-packages (from scikit-learn>=0.20.0->category_encoders) (2.1.0)
Requirement already satisfied: joblib>=0.11 in c:\users\stefa\anaconda3\lib\site-packages (from scikit-learn>=0.20.0->category_encoders) (1.0.1)
Installing collected packages: category-encoders
Successfully installed category-encoders-2.3.0
Note: you may need to restart the kernel to use updated packages.

In [1]:
import pandas as pd
import numpy as np

import category_encoders as ce

In [2]:
# pip install category_encoders
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [68]:
readmission_df = pd.read_csv('diabetic_data.csv')
readmission_df['diag_1'].head()

0    250.83
1       276
2       648
3         8
4       197
Name: diag_1, dtype: object

In [4]:
readmission_df.columns

Index(['encounter_id', 'patient_nbr', 'race', 'gender', 'age', 'weight',
       'admission_type_id', 'discharge_disposition_id', 'admission_source_id',
       'time_in_hospital', 'payer_code', 'medical_specialty',
       'num_lab_procedures', 'num_procedures', 'num_medications',
       'number_outpatient', 'number_emergency', 'number_inpatient', 'diag_1',
       'diag_2', 'diag_3', 'number_diagnoses', 'max_glu_serum', 'A1Cresult',
       'metformin', 'repaglinide', 'nateglinide', 'chlorpropamide',
       'glimepiride', 'acetohexamide', 'glipizide', 'glyburide', 'tolbutamide',
       'pioglitazone', 'rosiglitazone', 'acarbose', 'miglitol', 'troglitazone',
       'tolazamide', 'examide', 'citoglipton', 'insulin',
       'glyburide-metformin', 'glipizide-metformin',
       'glimepiride-pioglitazone', 'metformin-rosiglitazone',
       'metformin-pioglitazone', 'change', 'diabetesMed', 'readmitted'],
      dtype='object')

In [69]:
# Drop: admission_source_id, payer_code, medical_specialty, number_inpatient, number_outpatient, number_emergency, weight, patient_nbr, medications
readmission_cleaned = readmission_df.drop(columns=['admission_source_id', 'payer_code', 'medical_specialty', 'number_inpatient', 'number_outpatient', 'number_emergency', 
                                                  'weight', 'patient_nbr', 'metformin', 'repaglinide', 'nateglinide', 'chlorpropamide', 'glimepiride', 'acetohexamide', 
                                                           'glipizide', 'glyburide', 'tolbutamide', 'pioglitazone', 'rosiglitazone', 'acarbose', 'miglitol', 'troglitazone',
                                                           'tolazamide', 'examide', 'citoglipton', 'insulin', 'glyburide-metformin', 'glipizide-metformin', 
                                                           'glimepiride-pioglitazone', 'metformin-rosiglitazone', 'metformin-pioglitazone', 'change', 'diabetesMed'])
readmission_cleaned['diag_1'].head()

0    250.83
1       276
2       648
3         8
4       197
Name: diag_1, dtype: object

In [70]:
readmission_cleaned = readmission_df.drop(columns=['admission_source_id', 'payer_code', 'medical_specialty', 'number_inpatient', 'number_outpatient', 'number_emergency', 
                                                  'weight', 'patient_nbr', 'metformin', 'repaglinide', 'nateglinide', 'chlorpropamide', 'glimepiride', 'acetohexamide', 
                                                           'glipizide', 'glyburide', 'tolbutamide', 'pioglitazone', 'rosiglitazone', 'acarbose', 'miglitol', 'troglitazone',
                                                           'tolazamide', 'examide', 'citoglipton', 'insulin', 'glyburide-metformin', 'glipizide-metformin', 
                                                           'glimepiride-pioglitazone', 'metformin-rosiglitazone', 'metformin-pioglitazone', 'change', 'diabetesMed'])

substring = "V"
for i in range (0, len(readmission_cleaned['diag_1'])):
    if substring in readmission_cleaned['diag_1'][i]:
        readmission_cleaned['diag_1'][i]='2'
        
for i in range (0, len(readmission_cleaned['diag_2'])):
    if substring in readmission_cleaned['diag_2'][i]:
        readmission_cleaned['diag_2'][i]='2'
        
for i in range (0, len(readmission_cleaned['diag_3'])):
    if substring in readmission_cleaned['diag_3'][i]:
        readmission_cleaned['diag_3'][i]='2'
        
substring = "?"
for i in range (0, len(readmission_cleaned['diag_1'])):
    if substring in readmission_cleaned['diag_1'][i]:
        readmission_cleaned['diag_1'][i]='2'
        
for i in range (0, len(readmission_cleaned['diag_2'])):
    if substring in readmission_cleaned['diag_2'][i]:
        readmission_cleaned['diag_2'][i]='2'
        
for i in range (0, len(readmission_cleaned['diag_3'])):
    if substring in readmission_cleaned['diag_3'][i]:
        readmission_cleaned['diag_3'][i]='2'

substring = "E"
for i in range (0, len(readmission_cleaned['diag_1'])):
    if substring in readmission_cleaned['diag_1'][i]:
        readmission_cleaned['diag_1'][i]='2'
        
for i in range (0, len(readmission_cleaned['diag_2'])):
    if substring in readmission_cleaned['diag_2'][i]:
        readmission_cleaned['diag_2'][i]='2'
        
for i in range (0, len(readmission_cleaned['diag_3'])):
    if substring in readmission_cleaned['diag_3'][i]:
        readmission_cleaned['diag_3'][i]='2'

<ipython-input-70-e4f51a4c42e1>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  readmission_cleaned['diag_1'][i]='2'
<ipython-input-70-e4f51a4c42e1>:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  readmission_cleaned['diag_2'][i]='2'
<ipython-input-70-e4f51a4c42e1>:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  readmission_cleaned['diag_3'][i]='2'
<ipython-input-70-e4f51a4c42e1>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  readmission_cleaned['diag_1'][i]='2'
<ipython-input-70-e4f51a4c42e1>:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  readmission_cleaned['diag_2'][i]='2'
<ipython-input-70-e4f51a4c42e1>:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  readmission_cleaned['diag_3'][i]='2'
<ipython-input-70-e4f51a4c42e1>:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  readmission_cleaned['diag_1'][i]='2'
<ipython-input-70-e4f51a4c42e1>:40: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  readmission_cleaned['diag_2'][i]='2'
<ipython-input-70-e4f51a4c42e1>:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  readmission_cleaned['diag_3'][i]='2'

In [73]:
readmission_cleaned['diag_1'].head()

0    250.83
1     276.0
2     648.0
3       8.0
4     197.0
Name: diag_1, dtype: object

In [74]:
for i in range (0, len(readmission_cleaned['diag_1'])):
    readmission_cleaned['diag_1'][i] = float(readmission_cleaned['diag_1'][i])
        
for i in range (0, len(readmission_cleaned['diag_2'])):
    readmission_cleaned['diag_2'][i] = float(readmission_cleaned['diag_2'][i])
        
for i in range (0, len(readmission_cleaned['diag_3'])):
    readmission_cleaned['diag_3'][i] = float(readmission_cleaned['diag_3'][i])

<ipython-input-74-7fe270861c49>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  readmission_cleaned['diag_1'][i] = float(readmission_cleaned['diag_1'][i])
<ipython-input-74-7fe270861c49>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  readmission_cleaned['diag_2'][i] = float(readmission_cleaned['diag_2'][i])
<ipython-input-74-7fe270861c49>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  readmission_cleaned['diag_3'][i] = float(readmission_cleaned['diag_3'][i])

In [75]:
# Making bins for diagnosis groups
# 'Circulatory','Respiratory','Digestive','Diabetes','Injury','Musculoskeletal','Genitourinary','Neoplasms','Other'
bin_names = ['Other','Neoplasms','Diabetes','Neoplasms','Other','Neoplasms','Other','Circulatory','Respiratory','Digestive','Genitourinary'
             ,'Other','Neoplasms','Musculoskeletal','Other','Neoplasms','Circulatory','Respiratory','Digestive','Genitourinary',
             'Neoplasms','Injury']
bins = [0,139,249.99,250.99,279,289,319,389,459,519,579,629,679,709,739,759,784,785,786,787,788,799,1000]
readmission_cleaned['diag_1'] = pd.cut(readmission_cleaned['diag_1'], bins, labels=bin_names, include_lowest=True, ordered = False)
readmission_cleaned['diag_2'] = pd.cut(readmission_cleaned['diag_2'], bins, labels=bin_names, include_lowest=True, ordered = False)
readmission_cleaned['diag_3'] = pd.cut(readmission_cleaned['diag_3'], bins, labels=bin_names, include_lowest=True, ordered = False)


readmission_cleaned.head()

,encounter_id,race,gender,age,admission_type_id,discharge_disposition_id,time_in_hospital,num_lab_procedures,num_procedures,num_medications,diag_1,diag_2,diag_3,number_diagnoses,max_glu_serum,A1Cresult,readmitted
0,2278392,Caucasian,Female,[0-10),6,25,1,41,0,1,Diabetes,Other,Other,1,None,None,NO
1,149190,Caucasian,Female,[10-20),1,1,3,59,0,18,Neoplasms,Diabetes,Neoplasms,9,None,None,>30
2,64410,AfricanAmerican,Female,[20-30),1,1,2,11,5,13,Other,Diabetes,Other,6,None,None,NO
3,500364,Caucasian,Male,[30-40),1,1,2,44,1,16,Other,Diabetes,Circulatory,7,None,None,NO
4,16680,Caucasian,Male,[40-50),1,1,1,51,0,8,Neoplasms,Neoplasms,Diabetes,5,None,None,NO

In [76]:
readmission_cleaned['readmitted'].value_counts()

NO     54864
>30    35545
<30    11357
Name: readmitted, dtype: int64

In [77]:
readmission_cleaned[readmission_cleaned['readmitted'] == '>30'].head()

,encounter_id,race,gender,age,admission_type_id,discharge_disposition_id,time_in_hospital,num_lab_procedures,num_procedures,num_medications,diag_1,diag_2,diag_3,number_diagnoses,max_glu_serum,A1Cresult,readmitted
1,149190,Caucasian,Female,[10-20),1,1,3,59,0,18,Neoplasms,Diabetes,Neoplasms,9,None,None,>30
5,35754,Caucasian,Male,[50-60),2,1,3,31,6,16,Circulatory,Circulatory,Diabetes,9,None,None,>30
7,63768,Caucasian,Male,[70-80),1,1,5,73,0,12,Circulatory,Respiratory,Diabetes,8,None,None,>30
10,28236,AfricanAmerican,Female,[40-50),1,1,9,47,2,17,Diabetes,Circulatory,Injury,9,None,None,>30
14,62256,AfricanAmerican,Female,[60-70),3,1,1,49,5,2,Respiratory,Injury,Genitourinary,8,None,None,>30

In [84]:
readmission_cleaned['Target'] = readmission_cleaned['readmitted'].apply(lambda x: 'High-risk' if x == '<30' else 'Low-risk')

readmission_cleaned.head()

,encounter_id,race,gender,age,admission_type_id,discharge_disposition_id,time_in_hospital,num_lab_procedures,num_procedures,num_medications,diag_1,diag_2,diag_3,number_diagnoses,max_glu_serum,A1Cresult,readmitted,Target
0,2278392,Caucasian,Female,[0-10),6,25,1,41,0,1,Diabetes,Other,Other,1,None,None,NO,Low-risk
1,149190,Caucasian,Female,[10-20),1,1,3,59,0,18,Neoplasms,Diabetes,Neoplasms,9,None,None,>30,Low-risk
2,64410,AfricanAmerican,Female,[20-30),1,1,2,11,5,13,Other,Diabetes,Other,6,None,None,NO,Low-risk
3,500364,Caucasian,Male,[30-40),1,1,2,44,1,16,Other,Diabetes,Circulatory,7,None,None,NO,Low-risk
4,16680,Caucasian,Male,[40-50),1,1,1,51,0,8,Neoplasms,Neoplasms,Diabetes,5,None,None,NO,Low-risk

In [85]:
readmission_cleaned2 = readmission_cleaned.drop(columns="readmitted")

In [88]:
# encode/get dummies: race, gender, age, admission_type_id, diag_1, diag_2, diag_3, number_diagnoses, max_glu_serum, A1Cresult
ce_OHE = ce.OneHotEncoder(cols=['race','gender', 'age', 'admission_type_id', 'diag_1', 'diag_2', 'diag_3', 'number_diagnoses', 'max_glu_serum', 'A1Cresult'])

readmission_encoded = ce_OHE.fit_transform(readmission_cleaned2)
readmission_encoded.head()

,encounter_id,race_1,race_2,race_3,race_4,race_5,race_6,gender_1,gender_2,gender_3,age_1,age_2,age_3,age_4,age_5,age_6,age_7,age_8,age_9,age_10,admission_type_id_1,admission_type_id_2,admission_type_id_3,admission_type_id_4,admission_type_id_5,admission_type_id_6,admission_type_id_7,admission_type_id_8,discharge_disposition_id,time_in_hospital,num_lab_procedures,num_procedures,num_medications,diag_1_1,diag_1_2,diag_1_3,diag_1_4,diag_1_5,diag_1_6,diag_1_7,diag_1_8,diag_1_9,diag_2_1,diag_2_2,diag_2_3,diag_2_4,diag_2_5,diag_2_6,diag_2_7,diag_2_8,diag_2_9,diag_3_1,diag_3_2,diag_3_3,diag_3_4,diag_3_5,diag_3_6,diag_3_7,diag_3_8,diag_3_9,number_diagnoses_1,number_diagnoses_2,number_diagnoses_3,number_diagnoses_4,number_diagnoses_5,number_diagnoses_6,number_diagnoses_7,number_diagnoses_8,number_diagnoses_9,number_diagnoses_10,number_diagnoses_11,number_diagnoses_12,number_diagnoses_13,number_diagnoses_14,number_diagnoses_15,number_diagnoses_16,max_glu_serum_1,max_glu_serum_2,max_glu_serum_3,max_glu_serum_4,A1Cresult_1,A1Cresult_2,A1Cresult_3,A1Cresult_4,Target
0,2278392,1,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,25,1,41,0,1,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,Low-risk
1,149190,1,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,3,59,0,18,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,Low-risk
2,64410,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,2,11,5,13,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,Low-risk
3,500364,1,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,2,44,1,16,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,Low-risk
4,16680,1,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,1,51,0,8,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,Low-risk

In [13]:
readmission_dict = readmission_final.to_dict()

In [ ]:
from sklearn.datasets import load_breast_cancer
from sklearn.decomposition import PCA
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC

In [87]:
%matplotlib inline
from matplotlib import pyplot as plt
from sklearn.datasets import make_classification
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [89]:
y = readmission_encoded.Target.values
X = readmission_encoded.drop(columns="Target").values

In [90]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [91]:
scaler = StandardScaler().fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [92]:
clf = RandomForestClassifier(random_state=1, n_estimators=500).fit(X_train_scaled, y_train)
print(f'Training Score: {clf.score(X_train_scaled, y_train)}')
print(f'Testing Score: {clf.score(X_test_scaled, y_test)}')

Training Score: 1.0
Testing Score: 0.8881377250216178